# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/stavdel/Code/Space Cal Project/OpenVR-SpaceCalibrator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/stavdel/Code/Space Cal Project/OpenVR-SpaceCalibrator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/stavdel/Code/Space Cal Project/OpenVR-SpaceCalibrator/CMakeFiles" "/home/stavdel/Code/Space Cal Project/OpenVR-SpaceCalibrator//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/stavdel/Code/Space Cal Project/OpenVR-SpaceCalibrator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gl3w

# Build rule for target.
gl3w: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gl3w
.PHONY : gl3w

# fast build rule for target.
gl3w/fast:
	$(MAKE) $(MAKESILENT) -f OpenVR-SpaceCalibrator/CMakeFiles/gl3w.dir/build.make OpenVR-SpaceCalibrator/CMakeFiles/gl3w.dir/build
.PHONY : gl3w/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f OpenVR-SpaceCalibrator/CMakeFiles/imgui.dir/build.make OpenVR-SpaceCalibrator/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named openvr-spacecalibrator

# Build rule for target.
openvr-spacecalibrator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openvr-spacecalibrator
.PHONY : openvr-spacecalibrator

# fast build rule for target.
openvr-spacecalibrator/fast:
	$(MAKE) $(MAKESILENT) -f OpenVR-SpaceCalibrator/CMakeFiles/openvr-spacecalibrator.dir/build.make OpenVR-SpaceCalibrator/CMakeFiles/openvr-spacecalibrator.dir/build
.PHONY : openvr-spacecalibrator/fast

#=============================================================================
# Target rules for targets named openvr-spacecalibratordriver

# Build rule for target.
openvr-spacecalibratordriver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openvr-spacecalibratordriver
.PHONY : openvr-spacecalibratordriver

# fast build rule for target.
openvr-spacecalibratordriver/fast:
	$(MAKE) $(MAKESILENT) -f OpenVR-SpaceCalibratorDriver/CMakeFiles/openvr-spacecalibratordriver.dir/build.make OpenVR-SpaceCalibratorDriver/CMakeFiles/openvr-spacecalibratordriver.dir/build
.PHONY : openvr-spacecalibratordriver/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gl3w"
	@echo "... imgui"
	@echo "... openvr-spacecalibrator"
	@echo "... openvr-spacecalibratordriver"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

